#!/bin/bash
# Autor: Fernando A. Damião - https://github.com/fadamiao
# Baseado em: https://gist.github.com/959880

KMZ=$1

if [ $# -ne 1 ]; then
	echo "-> Sintaxe: kmz2kml <Arquivo.kmz>"
	exit
fi

if [ -z $1 ]; then
	echo "-> Sintaxe: kmz2kml <Arquivo.kmz>"
	exit
fi

echo '--> Bem vindo ao kmz2kml <--'

if [ -f $KMZ ]; then
	echo '--> Começando a extração'
	base_name=${KMZ%\.*}
	if ( unzip -qq $KMZ &> /dev/null ); then
		echo '--> Feito... '
		mv doc.kml $base_name.kml
		echo "--> Arquivo extraído para $base_name.kml"
	else
		echo '--> Erro inesperado'
	fi
else
	echo "--> O arquivo $1 não existe. Abortando..."
fi
